
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import tucil1kripto.Vigenere;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anggi
 */
public class GUI extends javax.swing.JApplet {

	/**
	 * Initializes the applet GUI
	 */
	@Override
	public void init() {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the applet */
		try {
			java.awt.EventQueue.invokeAndWait(new Runnable() {
				public void run() {
					initComponents();
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the init() method to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        algorithm_key = new javax.swing.ButtonGroup();
        algorithm_method = new javax.swing.ButtonGroup();
        output_format = new javax.swing.ButtonGroup();
        input = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextArea_Input = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea_Output = new javax.swing.JTextArea();
        TextField_Key = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        FromFile = new javax.swing.JRadioButton();
        UserInput = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        VigenereCipher = new javax.swing.JRadioButton();
        VarianVigenere = new javax.swing.JRadioButton();
        Standard = new javax.swing.JRadioButton();
        Extended = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        ApaAdanya = new javax.swing.JRadioButton();
        Group5 = new javax.swing.JRadioButton();
        WithoutSpace = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextField_Location = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        jRadioButton4.setText("jRadioButton4");

        jRadioButton8.setText("jRadioButton8");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextArea_Input.setColumns(20);
        TextArea_Input.setRows(5);
        jScrollPane2.setViewportView(TextArea_Input);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 72, 246, -1));

        TextArea_Output.setColumns(20);
        TextArea_Output.setRows(5);
        jScrollPane3.setViewportView(TextArea_Output);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 295, 530, -1));

        TextField_Key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_KeyActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Key, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 210, 530, -1));

        jLabel2.setText("Input:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 21, -1, -1));

        jLabel3.setText("Key (max. 25 characters):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 181, -1, -1));

        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 239, -1, -1));

        input.add(FromFile);
        FromFile.setText("From file");
        FromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromFileActionPerformed(evt);
            }
        });
        getContentPane().add(FromFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 40, -1, -1));

        input.add(UserInput);
        UserInput.setText("User input");
        getContentPane().add(UserInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 40, -1, -1));

        jLabel4.setText("Algorithm:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 21, -1, -1));

        algorithm_key.add(VigenereCipher);
        VigenereCipher.setText("Vigenere Cipher");
        getContentPane().add(VigenereCipher, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 44, -1, -1));

        algorithm_key.add(VarianVigenere);
        VarianVigenere.setText("Varian Vigenere Cipher");
        getContentPane().add(VarianVigenere, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 72, -1, -1));

        algorithm_method.add(Standard);
        Standard.setText("Standard");
        getContentPane().add(Standard, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 44, -1, -1));

        algorithm_method.add(Extended);
        Extended.setText("Extended");
        getContentPane().add(Extended, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 74, -1, -1));

        jLabel5.setText("Output Format:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 106, -1, -1));

        output_format.add(ApaAdanya);
        ApaAdanya.setText("Apa adanya");
        getContentPane().add(ApaAdanya, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 131, -1, -1));

        output_format.add(Group5);
        Group5.setText("Group of 5");
        getContentPane().add(Group5, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 131, -1, -1));

        output_format.add(WithoutSpace);
        WithoutSpace.setText("Without space");
        getContentPane().add(WithoutSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 131, -1, -1));

        jButton2.setText("Decrypt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 239, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 375, -1, -1));

        jLabel7.setText("Output:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        TextField_Location.setText("C:\\Users\\Anggi\\Documents\\kuliah\\Semester 6\\Kripto\\output.txt");
        getContentPane().add(TextField_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, -1));

        jButton3.setText("Save To File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromFileActionPerformed

    private void TextField_KeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_KeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_KeyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vigenere encrypt = new Vigenere();
		
		if(input.isSelected(FromFile.getModel())){
			encrypt.encryptFile(TextArea_Input.getText(), TextField_Key.getText());
		} else { // User Input
			encrypt.encryptInput(TextArea_Input.getText(), TextField_Key.getText());
		}
		
		if((algorithm_key.isSelected(VigenereCipher.getModel())) && (algorithm_method.isSelected(Standard.getModel()))){
			encrypt.encryptVigenereCipherStandard();
		} else if((algorithm_key.isSelected(VarianVigenere.getModel())) && (algorithm_method.isSelected(Standard.getModel()))){
			encrypt.encryptVarianVigenereStandard();
		} else if((algorithm_key.isSelected(VigenereCipher.getModel())) && (algorithm_method.isSelected(Extended.getModel()))) {
			encrypt.encryptVigenereCipherExtended();
		} else { // Varian Vigenere Extended
			encrypt.encryptVarianVigenereExtended();
		}
		
		if(output_format.isSelected(ApaAdanya.getModel())){
			//DO NOTHING
		} else if (output_format.isSelected(Group5.getModel())){
			encrypt.ciphertextGroupOfFive();
		} else { // without space
			encrypt.ciphertextWithoutSpace();
		}
		TextArea_Output.setText(encrypt.getCiphertext());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Vigenere decrypt = new Vigenere();
		
		if(input.isSelected(FromFile.getModel())){
			decrypt.decryptFile(TextArea_Input.getText(), TextField_Key.getText());
		} else { // User Input
			decrypt.decryptInput(TextArea_Input.getText(), TextField_Key.getText());
		}
		
		if((algorithm_key.isSelected(VigenereCipher.getModel())) && (algorithm_method.isSelected(Standard.getModel()))){
			decrypt.decryptVigenereCipherStandard();
		} else if((algorithm_key.isSelected(VarianVigenere.getModel())) && (algorithm_method.isSelected(Standard.getModel()))){
			decrypt.decryptVarianVigenereStandard();
		} else if((algorithm_key.isSelected(VigenereCipher.getModel())) && (algorithm_method.isSelected(Extended.getModel()))) {
			decrypt.decryptVigenereCipherExtended();
		} else { // Varian Vigenere Extended
			decrypt.decryptVarianVigenereExtended();
		}
		
		TextArea_Output.setText(decrypt.getPlaintext());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PrintWriter out = null;
		try {
			out = new PrintWriter(TextField_Location.getText());
		} catch (FileNotFoundException ex) {
			System.out.println(ex.getMessage());
		}
		out.println(TextArea_Output.getText());
		out.close();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ApaAdanya;
    private javax.swing.JRadioButton Extended;
    private javax.swing.JRadioButton FromFile;
    private javax.swing.JRadioButton Group5;
    private javax.swing.JRadioButton Standard;
    private javax.swing.JTextArea TextArea_Input;
    private javax.swing.JTextArea TextArea_Output;
    private javax.swing.JTextField TextField_Key;
    private javax.swing.JTextField TextField_Location;
    private javax.swing.JRadioButton UserInput;
    private javax.swing.JRadioButton VarianVigenere;
    private javax.swing.JRadioButton VigenereCipher;
    private javax.swing.JRadioButton WithoutSpace;
    private javax.swing.ButtonGroup algorithm_key;
    private javax.swing.ButtonGroup algorithm_method;
    private javax.swing.ButtonGroup input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.ButtonGroup output_format;
    // End of variables declaration//GEN-END:variables
}
